### ISSUE TITLE
CO-RE

### ISSUE THREAD

**Issue by HDwayne** [eBPF-MojitOS/eBPF-MojitOS#4]
la possibilité de compiler ou d'utiliser les fichier qu'on aura pre-compiler. avec une préférence sur le pre-compilé et en cas de problème laisser l'utiisateur recompiler le tout

**Comment by GrofZout** [comment]
On utilise libbpf qui implémente CO-RE. 
Cependant, il faut que je me renseigne pourquoi le programme compilé sur une nouvelle machine n'arrive pas à trouver le chemin vers libbpf.so.1.

**Comment by HDwayne** [comment]
Processur de compilation : 

- Compilation du code eBPF (bpf.c) en fichier objet (.o) : Cette étape transforme le code source eBPF en bytecode eBPF qui peut être chargé dans le noyau. (clang)

- Génération des fichiers .skel.h à partir du fichier .o : À l'aide de bpftool, les fichiers .skel.h sont générés. Ces fichiers contiennent des structures et des fonctions générées automatiquement qui facilitent l'interaction entre l'application utilisateur et le programme eBPF chargé dans le noyau.

- Compilation de l'application principale avec les fichiers .skel.h : l'application utilisateur est compilée en utilisant les fichiers .skel.h.

CO-RE :

- Si la version de libbpf change sur la machine cible ou si vous mettez à jour libbpf dans votre environnement de développement, il est conseillé de regénérer les fichiers .skel.h pour s'assurer qu'ils sont compatibles avec la version actuelle de libbpf. 

- Conservation du fichier .o : Le fichier objet eBPF (.o) reste valable tant que le code lui-même n'a pas changé. Si vous avez besoin de regénérer les fichiers .skel.h en raison d'une mise à jour de libbpf ou pour toute autre raison, utiliser les fichiers .o pour regénérer les fichiers .skel.h adaptés à la nouvelle version de libbpf.

Dans tout les cas on a besoin de libbpf installé sur la machine.
